### ISSUE TITLE
Visual indication of installation in progress

### ISSUE THREAD

**Issue by layday** [ogri-la/strongbox#179]
There appears to be no visual indication of an installation being in progress, which might lead one on a slow connection to think that an add-on failed to install and repeatedly attempt to install it.

**Comment by torkus** [comment]
I know. It's been in the TODO file since the beginning. The Undermine Journal is a large addon that appears to just hang before finally completing. 

This month I'm experimenting with JavaFX to see if I can get a GUI that is easier to style so components like progress bars inside tables become less arcane to implement.

**Comment by layday** [comment]
Closing since this is in your TODO :)

**Comment by torkus** [comment]
(and don't you have your own addon manager? or are you developing vicariously through others now? ;)

I don't mind this issue being opened or closed, it's something that is difficult to do in Swing but I suspect will be easier to do with JavaFX.

**Comment by layday** [comment]
> (and don't you have your own addon manager? or are you developing vicariously through others now? ;)

Well, I still like to use and contribute to other add-on managers if I can.  My GUI might not also be everybody's cuppa - it's a little unconvential when compared to the rest of the GUIs that are available.
