### ISSUE TITLE
cannot uninstall addon, "selection contains ignored addons"

### ISSUE THREAD

**Issue by sedlund** [ogri-la/strongbox#193]
Altoholic made a stub addon that upon loading saying they've changed the name to Altoholic-retail.

Tried to uninstall, and I get this error

![Screenshot_strongbox_20201014_132724_cannot_uninstall](https://user-images.githubusercontent.com/8109138/96030286-6ff57900-0e21-11eb-9aec-acc856235a41.png)

I tried 'Stop Un-ignoring' but it still gives the same error as above.

**Comment by torkus** [comment]
Sorry for the delay in replying. I appreciate the error message might seem a little obscure as well so I'll explain it.

Addons can overwrite each other. Installing an addon is simply unzipping an addon into a directory. Strongbox does some basic checks to make sure what you are installing *is* an addon, isn't corrupt, isn't writing anything outside of the addon directory etc, but it doesn't prevent one addon from overwriting another.

As of the last release, strongbox *does* track which addons are overwriting each other and keeps a track of that. It does this so that when you have two addons overlapping, uninstalling one doesn't remove the folders depended upon the other. It's a sticky mess but things mostly work most of the time.

Strongbox also has the feature to ignore addons. When you ignore an addon, Strongbox won't allow that addon to be overwritten by any other addon. It will refuse to install/update/uninstall that addon. If there are two addons overlapping and one of them is ignored, the other can't be uninstalled because that would affect the ignored addon.

So - if you have absolutely no addons being ignored, this is a bug. Otherwise, Altoholic has a mutual dependency with another, ignored, addon. This is because Altoholic and this other addon are sharing directories.

**Comment by torkus** [comment]
Also, I know it's a pain the arse, but I do appreciate the bug reports and screenshots. I can't test against everything found in the wild or how everybody's own personal set of addons will behave when put together, but it's very helpful so thank you for your patience.

**Comment by torkus** [comment]
I've just upgraded an older copy of Altoholic to the newer 9.0 'stub' version and it contains a new bundled addon called `Datastore_Rares`. What is special about this addon is that it's `.toc` file has this:

    ## Version: @project-version@

Which is unrendered template variable and one of things I look for when ***implicitly*** ignoring addons.

I didn't mention it above, so I'm sorry for that, but there are conditions under which an addon is ignored automatically (you will see warnings appear in your log window). For example, if it looks like an addon is under development (contains .git/.hg/.svn directories) or if the .toc file contains unrendered variables.

This is an 'upstream' problem with Altoholic.

It's not clear in your screenshot but your Altoholic addon is actually ignored like it's supposed to be, however an explicit 'stop ignoring' *isn't* working like it should and that is a bug I *can* address. I'll see it gets fixed before 3.0.0 is released.

**Comment by torkus** [comment]
Their [github releases](https://github.com/teelolws/Altoholic-Retail/releases) appears to have fixed this problem but the version being downloaded from Curseforge doesn't match anything I can find. I'll raise an issue with them.

**Comment by teelolws** [comment]
Looks like I slipped in a dev .toc into the redirect .zip I uploaded to the old project. Probably best if you just delete all the altoholic + datastore folders and reinstall it from the new link.

**Comment by torkus** [comment]
@sedlund , this has been fixed and I'll do another 3.0 pre-release this evening while I continue the hunt for a fix [for your other bug](https://github.com/ogri-la/strongbox/issues/191).

**Comment by torkus** [comment]
Released in 3.0.0
