### ISSUE TITLE
Dark theme - "addon has update" row color could be more clear

### ISSUE THREAD

**Issue by tstirrat** [ogri-la/strongbox#204]
**Is your feature request related to a problem? Please describe.**

The dark theme looks good on Mac, I had one addon update pending, but the color made it look like it was the currently selected addon. I like the yellow row in the light theme, can you make "has update" yellowish in the dark theme too?

**Comment by torkus** [comment]
thanks for opening a ticket, @tstirrat . 

I'll take a look at making the distinction between 'selected addon' and 'updateable addon' in the dark mode clearer.

The colours I'm using are following [a particular scheme](https://github.com/dracula/dracula-theme) that was requested. What I released [is definitely an improvement](https://github.com/ogri-la/strongbox/issues/192) over what was going to be put out but there is still room for polish.

**Comment by tstirrat** [comment]
Cheers. Yeah the dark theme is so much better than in 2.0. In 2.0 on Mac it barely worked!

 Darcula orange (`#ffb86c`) or green (`#50fa7b`) would be great for updated items.

**Comment by torkus** [comment]
current:
![Screenshot at 2020-12-26 22-43-09](https://user-images.githubusercontent.com/48790775/103151199-d60c5e00-47cb-11eb-9d7c-07ab211d7f34.png)

green:
![Screenshot at 2020-12-26 22-43-22](https://user-images.githubusercontent.com/48790775/103151194-d3aa0400-47cb-11eb-9322-da11150980e7.png)

orange:
![Screenshot at 2020-12-26 22-43-16](https://user-images.githubusercontent.com/48790775/103151197-d573c780-47cb-11eb-99c6-60397a5c6ec0.png)

they all look good in my opinion, but since the purpose of the ticket is to distinguish between the 'selected' colour and the 'updateable' colours (and probably the 'hover' colour), all of which are grey/dark grey/blue and kinda blend together, I might go with the green.

I think what I don't *quite* like about the colours above is how much they pop out. Here is the green but with black text:

![Screenshot at 2020-12-26 22-55-29](https://user-images.githubusercontent.com/48790775/103151385-a2323800-47cd-11eb-9c99-87601b77ea93.png)

Thoughts? I'm cc'ing @eVen-gits for his thoughts as well, as he helped with the current dark theme and might have ideas.

**Comment by eVen-gits** [comment]
Hello!

All I can add is my subjective opinion and I do agree that green with black text looks best out of these and it's all still in line with Dracula theme. Good input!

**Comment by torkus** [comment]
yeah, it's all subjective, I understand. Thanks for your feedback, @eVen-gits .

**Comment by torkus** [comment]
fixed in 3.2.0. The 'update' colour in the dark theme is now more distinct.

I ended up liking all of the above colours so I've added them in as separate themes.

Please let me know if this addressed your original problem, @tstirrat .

Thanks again guys.
