### ISSUE TITLE
Healbot Classic TBC not showing up when searched for

### ISSUE THREAD

**Issue by Ironlenny** [ogri-la/strongbox#261]
**Describe the bug**
See title

**To Reproduce**
*Steps to reproduce the behavior. For example:*
- Click the "Search" tab.
- Type "Healbot Classic TBC"
- See "No search results"

**Expected behavior**
You would see "Healbot Classic TBC" listed from wowinterface.com

**Comment by Ironlenny** [comment]
I'm using version 4.1.0 btw

**Comment by torkus** [comment]
I suspect it's because I update the catalogue once a week on the weekend. The last update was the 15th and this addon was uploaded just a couple of days ago on the 17th.

I've updated the catalogue again. You may need to go to *Cache* -> *Clear catalogues* for strongbox to remove it's local copies and reload itself.

**Comment by torkus** [comment]
I'm going to close this but let me know if you're still not seeing your addon.

**Comment by Ironlenny** [comment]
That fixed it. Thanks!
