### ISSUE TITLE
Unable to add Questie from Github

### ISSUE THREAD

**Issue by jecs** [ogri-la/strongbox#339]
**Describe the bug**
When I search for Questie and attempt to install Questie from github, I get the message "No Classic (TBC) release" found on github despite Questie having a BCC toc file.

**To Reproduce**
1. Go to Search
2. Search Questie
3. Install github version (not QuestieDev)

Sorry to bother. With the switch from Curseforge to other sources, I am scrambling to get all of these things in order. Thank you for all that you do!

**Comment by jecs** [comment]
I am also unable to add the BCC version of WeakAuras2:
https://github.com/WeakAuras/WeakAuras2

**Comment by torkus** [comment]
hey @jecs, thanks for opening an issue.

> Sorry to bother. With the switch from Curseforge to other sources, I am scrambling to get all of these things in order. Thank you for all that you do!

It's not a bother at all. If nobody opens issues I assume everything is working 100% fine. By reporting bugs you're helping me and everybody else using Strongbox, so, cheers!

Bit of a disclaimer for Github addons: a lot of guessing is involved. There are many different ways addon developers are using Github and strongbox tries to cater to most of them. Also, the way addon developers handle their releases *over time* may change, which I think might be the case with Questie.

With the game version set to `Classic (TBC)` and unchecking 'strict' I'm able to get Questie installed, but it installs version `6.2.6` and not the latest `6.8.3`. Changing the game version to `Retail` and updating the addon I can get `6.8.3` installed.

This is happening because their releases are not being classified and are defaulting to `retail` *except* for the `v6.2.6 - Classic` where `Classic` is right there in the name - that's a very common pattern and something we look for. When `Classic (TBC)` is selected and `strict` is off, it's going to install the closest version, which is `classic`.

Now, to add another layer to this problem, before the Github catalogue was introduced, Github addons had to be *imported* (`File -> Import addon`) and a more involved analysis would happen to figure out what game versions were supported. However, because of that one release of theirs, `v6.2.6 - Classic`, this process is being short-circuited as strongbox thinks it's discovered how the releases are being named and doesn't do any further checking.

Questie is also doing something weird with their [retail `.toc` file](https://github.com/Questie/Questie/blob/97467a46710c0e57ed8bd7a9e1532c3956704827/Questie.toc) that I need to check out.

I'll investigate these problems and see if I can't come up with a better strategy to classify github releases.

**Comment by torkus** [comment]
Sorry for the long delay in looking into this.

I *think* the original Questie problem with "No Classic (TBC) release"  has resolved itself. Not entirely sure how, but I can't replicate it any more.

The other problem I mentioned with the dodgy `.toc` file has [a fix here](https://github.com/ogri-la/strongbox/pull/364) but this shouldn't be affecting normal operation of strongbox.

I'm going to close this ticket when the above fix is released at the end of this month so if it's still giving you problems please speak up and I'll take another look at it.
