### ISSUE TITLE
Interface improvements

### ISSUE THREAD

**Issue by ilu33** [ogri-la/strongbox#352]
The interface is really confusing. That's why I migrated to wowup some time ago, but I like your attitude much better, so here are some proposals from a UI designer's point of view:

1. Change game version: There are 2 dropdown menus, one to change the directory, one to change the game version. They sync only in one direction - directory -> game version, but not the other way round. So if you don't pay attention you will overwrite your retail addons with classic versions or vice versa. Why are there 2 dropdowns in the first place? Directories do not get changed regularly, they should be defined under a settings menu. The game version dropdown should be authoritative.
2. Table headers are confusing: Is "version" the present version or the version of the available update? Is "WoW" the present game version (which is always the same and thus not necessary), the toc version of the present addon or the toc version of the addon update? 
3. The user needs to see the columns "installed" and "available". That is important, see my issue about addon version mixups (tbd).
4. Ignoring an addon (because the local copy is newer) changes the addon name into info<ID>(group). Not nice.
5. (solved)
6. The icon used with the tooltip "Update available" is much too small and weird - universally accepted is an arrow pointing down. The right-arrow is used to mean "next" but if you click on it nothing happens.
Edit: After several retries another tab opens but it does not have any additional information, just the update buttons.
7. Some addons (notably BigWigs) use color coding in their toc, which is stupid but nonetheless existing. i|cfffffaaCPU|r is not really a name, but iCPU is, can this be parsed in a better way?
8. No way to tell strongbox that an addon is part of a group? File -> "Re-install all" is not really a solution, this might overwrite a lot of addons where no new source is available. Edit: There's a right-click option to only re-install the one addon and that works. But there are some I cannot reinstall because there is no available online source.
9. No way to tell strongbox another source?
10. How to tell strongbox that the local version has changed after a manual update from a zip file?
11. No way to copy the error console messages in order to paste them here - no copy-paste anywhere, really.

**Comment by ilu33** [comment]
> This is what the 'strict' checkbox is for.

Strict is checked. Should I uncheck it? I do not really understand what "strict" means in this context. Whether I check it or not - if I change the dropdown to "classic" because I want to update those addons I still see the retail directory with the retail addon.

> 
> Explicitness vs implicitness, preferring explicitness in general. Visible vs hidden, preferring visible in general. There is a school of design where uncommon features should be removed and those features that can't be removed should be hidden, leaving a minimal 'essential' interface to a magically behaving application. I don't subscribe to that.

I can understand this. I'm not adhering to any school of design, I'm just trying to take the view of a "normal" user - and to them this is confusing. I've tested among friends. 
Same goes for the table headers. I understand that you thought about it and implemented that way but someone new to strongbox has no idea what you thought. If the content of the column changes after an update check (like you said) this needs to be made visible. Otherwise nobody knows about that change.
Easiest solution would be to make 'installed' and 'available' columns default.

> Double-clicking a row will open the 'addon detail' tab.

That's good. Took me a while to realize. 
I still think the icon should be the universally used down-arrow. And a bit bigger.

> This one is on my [TODO list](https://github.com/ogri-la/strongbox/blob/develop/TODO.md?plain=1) actually. It's been a pita since the beginning.

I believe. Great.

> > No way to tell strongbox that an addon is part of a group? 
> > No way to tell strongbox another source?
 
Well, the problem comes up when strongbox does not find another source. But there might be a source I could enter by hand (github, gitlab, local ZIP file, or anywhere really). Even if the automatic update does not work, at least that would be a note for me doing it manually. Whatever we thing about the curseforge changes we will need to update half our addons by hand and I have no hope that that will change.
Local directory for ZIP files would be a good idea, actually.

Also consolidating groups by hand that don't have an available source anymore would be useful. I thought I could do that by changing the .strongbox.json but changes there do no seem to get read?

> > No way to copy the error console messages in order to paste them here - no copy-paste anywhere, really.
> 
> Fair enough, this can be improved. You _can_ run Strongbox from the terminal however and everything you see in the console will be printed there as well, including stacktraces. If you're seeing errors there are steps in the 'bug report' issue type that will help me to debug your problem.

Will do that next time.

Anyway, this is not me nitpicking. I really appreciate your work and because of that I invested quite some time into these issues.

**Comment by torkus** [comment]
> Strict is checked. Should I uncheck it? I do not really understand what "strict" means in this context. Whether I check it or not - if I change the dropdown to "classic" because I want to update those addons I still see the retail directory with the retail addon.

'strict' will ensure only addons matching the game version of the addon directory are installed. If the addon directory's game version is 'retail', 'strict' will ensure only retail addons are installed into it.

Unchecking 'strict' will allow you to install classic and classic-tbc addons into an otherwise retail addon directory. Same goes for 'classic' and 'classic-tbc'. There is often ambiguity in what an addon supports because of the addon host or because a heuristic in Strongbox fails and strictness needs to be relaxed temporarily to allow an update to happen.

> Also consolidating groups by hand that don't have an available source anymore would be useful. 

If there is no alternative source to be found, and nothing similar found in the catalogue, then you're stuck with an addon that won't get updated anymore. I would either 'ignore' the addon preventing future updates or uninstall it.

> I thought I could do that by changing the .strongbox.json but changes there do no seem to get read?

Those files definitely get read, they tie addons on the filesystem to addon in the catalogue. I'm not sure what sorts of edits you were trying to do here though. From your other ticket it sounds like Strongbox thought whatever you did was invalid and deleted a bunch of them.

---

From this feedback these are the points I'm taking on board:

* manually select a primary addon from a group of addons to prevent synthetic titles
* bumping priority of the markup parser used to encode colours
* better copying from the interface, especially the log box
* highlighting changed values in the 'version' column when an addon has an update available
* consider a means to manually group ungrouped addons ... this one seems quite complicated for little benefit though.

Manually installing addons by unzipping them outside of Strongbox is *always* going to mess with it's state. The data in the `.strongbox.json` file, mostly taken from the addon host/catalogue, takes precendence over whatever is scraped from the toc files. I expect the feature I introduce next month to allow installing local zip files will help this. 

...If I were to allow the refresh of the `.strongbox.json` 'version' values from what is inside the .toc file, then Strongbox would still prompt you to update because the .toc file 'version' doesn't match the 'version' in the catalogue.

**Comment by ilu33** [comment]
> From this feedback these are the points I'm taking on board

That will definitely improve things. Thank you.

> Manually installing addons by unzipping them outside of Strongbox is _always_ going to mess with it's state. ...

Yeah, well, I'd obviously prefer if this was not necessary but almost half my addons are from curse and don't have another source that's up to date. I don't expect this to change because at least some of them are made by known active authors and they most probably know why they are doing this (and why they don't update wowinterface even if they used it once upon a time).

**Comment by torkus** [comment]
I've added your points to my TODO file.

Work has started on installing zipfiles manually through Strongbox here: https://github.com/ogri-la/strongbox/pull/357

(I can't guarantee when any of these will be released)
