### ISSUE TITLE
Addon version mixups: some addons show as "Updates" although they are downgrades

### ISSUE THREAD

**Issue by ilu33** [ogri-la/strongbox#354]
Some addons show up as "Updates" although they are in reality downgrades.
Notably: 
https://www.wowinterface.com/downloads/info4459-Bagnon.html from 2019
https://www.wowinterface.com/downloads/info23141-BugGrabber.html 9.2.2
https://www.wowinterface.com/downloads/info21063-AutoTurnIn.html 7.5.1 2020 (shown as 9.0.1 for some reason)
https://www.wowinterface.com/downloads/info11187-Postal 3.6.6. 2020
https://www.wowinterface.com/downloads/info14790-RaidAchievement.html 9.150 2021
https://www.wowinterface.com/downloads/info23999-WorldQuestTracker.html v8.2.5.384 2019

All have newer versions on curseforge that should be kept. The user really needs to see the columns "installed" and "available" as a default to prevent downgrades. Ideally strongbox should prevent downgrades because now clicking "update all" is not safe. Especially if https://github.com/ogri-la/strongbox/pull/263 gets merged! 

Putting the addon on "Ignore" does not really help because one fine day an upgrade might show up which you will then miss. And ignore triggers name changes.

Another problem: strongbox refuses to update the BigWigs_Classic module for retail because it has "classic" in its name.

**Comment by torkus** [comment]
> Some addons show up as "Updates" although they are in reality downgrades.

The version strings are not scrutinised beyond simply being different. Strongbox doesn't make a judgement about whether the latest available update is a downgrade or upgrade, safe, stable, etc. 

If this is the first time Strongbox has seen that addon then it doesn't know where it came from.

> All have newer versions on curseforge that should be kept. 

No Curseforge support means a whole lot of addons that are available exclusively through Curseforge are no longer available. If you're seeing extreme differences if versions between Curse and wowi then I suggest contacting the addon author and politely asking if they could update wowinterface, or if they use a github repository.

> [...] And ignore triggers name changes.

Not sure what you mean by that, could you elaborate please?

> Another problem: strongbox refuses to update the BigWigs_Classic module for retail because it has "classic" in its name.

Is this the github source of BigWigs_Classic? An awful lot of guessing happens for github addons while trying to figure out which game versions exist. In fact, I'm guessing at your problem right now. If you want me to help further with this one you're going to have provide me with a few more details. When you created this bug report there were steps that were suggested you should follow to help me recreate the problem you're seeing. I'll print them again below:

---

**Describe the bug**
*A clear and concise description of what the bug is.*

**To Reproduce**
*Steps to reproduce the behavior. For example:*
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Additional context**
Anything else that may help. Strongbox can be run with the `--debug` flag and the log file it generates can be attached to this bug report. For example, `java -jar strongbox.jar --debug` and the path to the log file is printed on application exit.

**Comment by ilu33** [comment]
> The very wide variety and inconsistency of version strings doesn't make this feasible.

I get the problem now.

Pity that I can't modifying the `.strongbox.json` files. 

> I can't help you further on this one if you don't read instructions. I need to know the state of the addon and your addon directory to recreate what is happening. To do this you need to run strongbox with the `--debug` flag and paste the results.

There is nothing about BigWigs_Classic or the ID 22095 in the log file except what was shown in the picture:
```
04:13:16.094  INFO [strongbox.core:417] - writing logs to: /home/...
04:13:16.103  INFO [strongbox.utils:43] - instrumentation is OFF
04:13:16.663  INFO [strongbox.ui.jfx:2579] - starting gui
04:13:16.676  INFO [strongbox.core:417] - writing logs to: /home/...
04:13:17.404  DEBUG [strongbox.http:144] - cache hit for: https://api.github.com/repos/ogri-la/strongbox/releases/latest (/home/xxx/.local/share/strongbox/cache/aHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy9vZ3JpLWxhL3N0cm9uZ2JveC9yZWxlYXNlcy9sYXRlc3Q=.html)
04:13:20.092  REPORT [strongbox.core:1300] - refresh
04:13:20.184  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.186  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.188  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.195  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.226  WARN [strongbox.toc:152] - ':classic' from filename does not match it's interface-version ':retail'
04:13:20.250  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ## Version 3.0.12
04:13:20.260  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ## Version 3.0.12
04:13:20.262  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ## Version 3.0.12
04:13:20.277  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.279  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.288  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.290  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.298  DEBUG [strongbox.toc:34] - cannot parse line, ignoring: ##
04:13:20.301  WARN [strongbox.toc:152] - ':classic' from filename does not match it's interface-version ':retail'
04:13:20.344  WARN [strongbox.addon:172] - multiple sets of different toc data found for :retail. using first.
04:13:20.416  WARN [strongbox.addon:172] - multiple sets of different toc data found for :retail. using first.
04:13:20.446  WARN [strongbox.toc:152] - ':classic' from filename does not match it's interface-version ':retail' 
...
04:13:22.803 asus10 INFO [strongbox.core:?] - found in catalogue with source "wowinterface" and id "22095"
...
04:13:24.449 asus10 DEBUG [strongbox.http:144] - cache hit for: https://api.mmoui.com/v3/game/WOW/filedetails/22095.json (/home/.../.local/share/strongbox/cache/aHR0cHM6Ly9hcGkubW1vdWkuY29tL3YzL2dhbWUvV09XL2ZpbGVkZXRhaWxzLzIyMDk1Lmpzb24=.json)
```

There is no more mention of neither BigWigs_Classic nor 22095 nor strongbox.toc:152. The log includes personal information and is too big to sanitize it.
 
The terminal output has some more information:
```
04:13:20.226 [warn] [BigWigs_Classic] ':classic' from filename does not match it's interface-version ':retail'
04:13:22.803 [info] [BigWigs_Classic] found in catalogue with source "wowinterface" and id "22095"
04:13:24.449 [debug] [BigWigs_Classic] cache hit for: https://api.mmoui.com/v3/game/WOW/filedetails/22095.json (/home/.../.local/share/strongbox/cache/aHR0cHM6Ly9hcGkubW1vdWkuY29tL3YzL2dhbWUvV09XL2ZpbGVkZXRhaWxzLzIyMDk1Lmpzb24=.json)
```

I cannot trigger any operation on BigWigs_Classic because the right-click menu (update, reinstall) is grey.

**Comment by torkus** [comment]
If I understand your problem correctly then I think I've replicated it.

1. set addon dir to 'retail' and 'strict'
2. install 'Bigwigs_Classic' from the 'Github' source
3. Strongbox says no:

![Screenshot at 2022-05-22 11-17-18](https://user-images.githubusercontent.com/48790775/169674885-f663e54a-ecfd-422c-a375-64a5351291d7.png)

The workaround is to turn off 'strict' temporarily.

Lots of guessing has to happen for Github hosted addons and they're also a relatively recent addition so it's never going to be perfect, but it can definitely be a little better.

I've added this bug to my TODO list and am closing this ticket now. The other issue of upgrades vs downgrades by comparing version strings is not feasible, especially across addon hosts.
