### ISSUE TITLE
Cannot import addon from wowinterface, says "Couldn't find addon in catalogue 'full'

### ISSUE THREAD

**Issue by thembees** [ogri-la/strongbox#365]
I click file, import addon, and paste https://www.wowinterface.com/downloads/info20927-ElvUIShadowLight.html , because it won't show shadow & light in the search tab, and it comes up and says: 
![image](https://user-images.githubusercontent.com/106179211/173202159-6d5b1c6d-5f03-4fac-b1fc-4ca40d3a4bf8.png)
 
![image](https://user-images.githubusercontent.com/106179211/173202167-93669b86-4f17-45c7-b855-58a9421a18d1.png)

ElvUI is searchable and installs, as well as a ton of other addons: 
![image](https://user-images.githubusercontent.com/106179211/173202192-c37f6229-eba7-4e1c-8d83-eaa69addca73.png)

**Comment by torkus** [comment]
hey @thembees , thanks for opening a ticket.

I've taken a quick look as to why this addon isn't appearing in the catalogue, and it's because it's missing from the wowinterface API.

I don't know what causes an addon to be excluded from the API, I can see plenty of other elvui addons hosted on wowinterface, but I think at last count there were about 3k addons that wowinterface have on their website that can't be found through their API.

You're not doing anything wrong, it's just a weird state you've encountered.

Sorry I couldn't be more helpful.
