### ISSUE TITLE
Issues updating Tukui/ElvUI

### ISSUE THREAD

**Issue by RipleyTom** [ogri-la/strongbox#407]
When checking for ElvUI update(from tukui source) on strongbox 6.1.2:
```
15:52:51.595 [error] [ElvUI] failed to parse json: JSON error (unexpected character): <
15:52:51.596 [error] [ElvUI] failed to parse json: JSON error (unexpected character): <
15:52:51.596 [error] [ElvUI] failed to parse json: JSON error (unexpected character): <
15:52:51.597 [error] [ElvUI] failed to parse json: JSON error (unexpected character): <
```

I imagine something changed in the api.

**Comment by torkus** [comment]
Thanks for opening a ticket. 

This is because Tukui.org is dead and they haven't announced anything. 

They've changed the location of their API, the behaviour of their API and the new API will only host two addons: tukui and elvui.

There is a bit more here: https://github.com/ogri-la/strongbox/issues/405

I'm not sure of the actual circumstances but I'll probably be removing tukui support. It's an awful lot of code to maintain for just two addons. I may mirror them on Github (somehow) and incorporate them into the Github catalogue.

Sorry for the inconvenience :(

**Comment by torkus** [comment]
> When checking for ElvUI update(from tukui source) on strongbox 6.1.2:
> 15:52:51.595 [error] [ElvUI] failed to parse json: JSON error (unexpected character): <

We're being served a 404 now rather that being redirected back to the (html, non-json) landing page so Strongbox is returning the more helpful "Not Found" error:

![Screenshot at 2023-06-02 22-31-32](https://github.com/ogri-la/strongbox/assets/48790775/e21d7143-9848-408e-b6b5-8fef8469c8d8)

**Comment by torkus** [comment]
I've created a Github mirror of Tukui and ElvUI here:

* https://github.com/ogri-la/tukui
* https://github.com/ogri-la/elvui

They haven't been incorporated into the Github catalogue that Strongbox uses, but you can import them with `File -> Import addon` and then pasting in the above urls. 

This will replace the tukui-installed version of the addon (if it exists) in the same way that Curseforge addons were being replaced by addons from other sources when their support was dropped.

![Screenshot at 2023-06-03 23-06-06](https://github.com/ogri-la/strongbox/assets/48790775/ed52a415-8613-4db1-a0f2-46f3039f8e5b)

I'm working on automating the process so new releases can be picked up and published automatically, as well as the automation script for transparency's sake.

If there is anything you'd like to see just let me know.

I'll close this ticket when I've automated mirroring their releases.

**Comment by RipleyTom** [comment]
It works fine, thank you for the quick fix!

**Comment by nhaz99** [comment]
Hello, so to be clear,  my account on tukui.org is dead and life subscription too i suppose ? where we have to subscribe and pay now pls ? thx

**Comment by AcidWeb** [comment]
> This is because Tukui.org [as we knew it] is dead and they haven't announced anything.

I'm aware this change was quick due to multiple reasons but here was announcement on our Discord server - it is a heart of our community. Plus I came here specifically to inform you a few days earlier.

I don't know what to think about this GH mirror. I would really appreciate if it would use our API directly.

**Comment by torkus** [comment]
hi @nhaz99,

> Hello, so to be clear, my account on tukui.org is dead and life subscription too i suppose ? where we have to subscribe and pay now pls ? thx

I suppose so. If you paid for a service and it wasn't provided then a refund seems reasonable, like in any walk of life.

tukui.org have a Github organisation here where you could raise your issue:
https://github.com/tukui-org

best of luck

**Comment by torkus** [comment]
> I would really appreciate if strongbox would use our API directly.

Two addons is too small for special attention. 

I recommend hosting your releases on wowinterface or on github.com then there won't be any need to mirror them.

**Comment by AcidWeb** [comment]
If GH CDN would handle our traffic spikes correctly this whole discussion would not exist. We hit similar issues that XIVLauncher had.

Using WoWI is like switching from completely abandoned infrastrukture to almost completely abandoned infrastructure.

**Comment by AcidWeb** [comment]
> Hello, so to be clear, my account on tukui.org is dead and life subscription too i suppose ? where we have to subscribe and pay now pls ? thx

You never had to pay and your subscription is probably still enabled. Use your Discord (https://discord.gg/xFWcfgE) ticketing system if you have more questions/issues.

**Comment by torkus** [comment]
Release mirroring is automated now, it's checked every hour.

@AcidWeb , my traffic can be identified through the user agent:

    "tukui-mirror-script/1.x (https://github.com/ogri-la/tukui-mirror-script)"

The mirror script can be found here: https://github.com/ogri-la/tukui-mirror-script

The mirrored addons are incorporated into the catalogue of Github addons that Strongbox uses, that is compiled using an older version of @layday's work, but both Strongbox and Instawow should have ogri-la/tukui and ogri-la/elvui available to them now.

Strongbox will automatically match installed versions of tukui and elvui to the Github catalogue and issue a warning about the source of the addon changing but otherwise won't prevent the update from happening.

Strongbox 7.0.0 has also just been released that removes tukui.org support.

Thanks everyone for your feedback.

As always, if there are any problems please just open a ticket.
