### ISSUE TITLE
Consider creating a submission on flathub

### ISSUE THREAD

**Issue by Lordakius** [ogri-la/strongbox#415]
I would love to see this project be available more generally, would you consider submitting this to [flathub](https://docs.flathub.org/docs/for-app-authors/submission/)? 

As said in their FAQ it is preferred for maintainers to submit their own projects, but if you don't have the time for that, I can submit it (with your permission).

**Comment by torkus** [comment]
I've been meaning to investigate flatpaks since the Steam Deck came out, unfortunately they were never made available in my part of the world so my interest tapered off.

Recently I've been playing with Fedora on a Surface Pro 2 to see what Linux-as-a-tablet is like (*surprisingly good*) and Fedora makes use of flatpaks as well.

Strongbox is distributed as a `.jar` as well as an `.AppImage` so could feasibly live on https://www.appimagehub.com too. Another aggregate of `.AppImage` files is https://appimage.github.io/apps/

I'm happy to revisit changes in packaging and distribution. A `7.1.0` release is due soon with some minor features, tweaks and bugfixes, I'll see if I can coordinate improved packaging with it.

Regarding other types of packaging, I won't be touching Canonical's [snaps](https://snapcraft.io). Just like their upstart and unity products, I think the motivation behind them is suspect and destined to be discontinued. 

Ultimately, nobody needs my permission to create a distribution of Strongbox. If you (or anyone else) feel so motivated to create a distribution of Strongbox then my only *preference* is that it's marked as **unofficial** in some way.

**Comment by torkus** [comment]
I think you misunderstood me:

> I'm happy to revisit changes in packaging and distribution. A 7.1.0 release is due soon with some minor features, tweaks and bugfixes, I'll see if I can coordinate improved packaging with it.

I'll probably have some time this weekend to look at using flatpaks to package strongbox, but there probably won't be a release until 7.1.0 comes out

**Comment by torkus** [comment]
well, here we are on flathub: 
https://flathub.org/en-GB/apps/la.ogri.strongbox

and in some distinguished company too:
![Screenshot at 2023-11-17 22-09-32](https://github.com/ogri-la/strongbox/assets/48790775/769f9b87-cea7-401c-8a0e-3692ee7a561f)

thanks for opening a ticket @Lordakius, let me know if it doesn't work for you
